
export default [
    {

        type:"text",
        name:"id",
        hide:true,
        label:"id"
    },
    {
        type:"text",
        name:"name",
        label:"规则名称",
        headerAble:true,
        filterAble:true,
    },
    {
        type:"select",
        name:"type",
        label:"规则类型",
        filterAble:true,
        value:"01",
        data:[
            {
                value:"01",
                text:"存款"
            },
            {
                value:"02",
                text:"收益"
            }
        ]
    },
    {
        type:"textarea",
        name:"description",
        label:"描述",
    }
]